import { z } from "zod";
import {
  PICTOGRAM_GRID,
  UNSUPPORTED_PICTOGRAM,
  isIgnoredCodepoint,
  looksLikeSymbol,
  pictogramFor,
  pictogramScale,
  type Pictogram,
} from "./render/pictograms";

/**
 * Pre-rasterised glyph atlas format, version 2.
 *
 * Generated by tools/gen_font_atlas.py from the OFL faces vendored in
 * assets/fonts/. Runtime drawing is pure array blitting: deterministic, no
 * native dependency, byte-identical in Node and in the browser, which is what
 * lets the designer preview claim to be the same renderer that packs the
 * device bytes.
 *
 * Version 2 changed two things, both in response to the panel looking lumpy:
 *
 *   * Glyphs come from FreeType's monochrome hinted rasteriser rather than
 *     from an anti-aliased render cut at alpha >= 110. Hinting grid-fits the
 *     whole outline before sampling, so stems are snapped to whole pixels as
 *     a set instead of each one rounding on its own.
 *   * Advances are whole pixels, taken in that same mode. A fractional
 *     advance lets the pen drift off the pixel grid between letters, which
 *     undoes the hinting one glyph later.
 *
 * tools/raster_lab.py and tools/raster_fidelity.py measure both claims.
 */

export const FONT_FAMILY_IDS = [
  "inter",
  "atkinson",
  "plexmono",
  "poppins",
] as const;
export type FontFamilyId = (typeof FONT_FAMILY_IDS)[number];

export const FONT_WEIGHTS = ["regular", "bold"] as const;
export type FontWeight = (typeof FONT_WEIGHTS)[number];

/**
 * The size ladder. Discrete because every size has to be rasterised and
 * committed: a free-text size box would offer sizes that have no atlas.
 *
 * The floor is 11 px. The panel previously drew as small as 10 px, and that
 * is the size the owner rejected by eye on the physical panel.
 */
export const FONT_SIZES = [11, 13, 15, 18, 22, 27, 34, 48, 64] as const;
export type FontSize = (typeof FONT_SIZES)[number];

export function isFontSize(value: unknown): value is FontSize {
  return (
    typeof value === "number" && (FONT_SIZES as readonly number[]).includes(value)
  );
}

/** The next size up or down the ladder, clamped at the ends. */
export function stepFontSize(size: FontSize, direction: 1 | -1): FontSize {
  const index = FONT_SIZES.indexOf(size);
  const next = Math.min(
    FONT_SIZES.length - 1,
    Math.max(0, index + direction),
  );
  return FONT_SIZES[next] as FontSize;
}

export const GlyphSchema = z.object({
  /** Horizontal pen advance in whole pixels, hinted. */
  a: z.number().int().nonnegative(),
  /** Bitmap left offset from the pen position. */
  l: z.number().int(),
  /** Bitmap top offset from the ascender origin (positive is downward). */
  t: z.number().int(),
  /** Bitmap width in pixels. */
  w: z.number().int().nonnegative(),
  /** Bitmap height in pixels. */
  h: z.number().int().nonnegative(),
  /** Rows of 1bpp coverage, MSB first, each row padded to a byte. Base64. */
  b: z.string(),
});
export type Glyph = z.infer<typeof GlyphSchema>;

export const FontAtlasSchema = z.object({
  family: z.enum(FONT_FAMILY_IDS),
  weight: z.enum(FONT_WEIGHTS),
  size: z.number().int().positive(),
  ascent: z.number().int(),
  descent: z.number().int(),
  lineHeight: z.number().int().positive(),
  glyphs: z.record(z.string(), GlyphSchema),
});
export type FontAtlas = z.infer<typeof FontAtlasSchema>;

export const FontAtlasFileSchema = z.object({
  schema_version: z.literal(2),
  family: z.enum(FONT_FAMILY_IDS),
  label: z.string(),
  raster: z.literal("freetype-mono-hinted"),
  licence: z.string(),
  atlases: z.record(z.string(), FontAtlasSchema),
});
export type FontAtlasFile = z.infer<typeof FontAtlasFileSchema>;

export function atlasKey(weight: FontWeight, size: number): string {
  return `${weight}-${size}`;
}

/** Decoded glyph bitmap, one byte per pixel, 1 where the glyph covers. */
export interface DecodedGlyph extends Glyph {
  mask: Uint8Array;
}

const decodeCache = new WeakMap<Glyph, DecodedGlyph>();

function base64ToBytes(value: string): Uint8Array {
  if (value.length === 0) return new Uint8Array(0);
  if (typeof atob === "function") {
    const binary = atob(value);
    const out = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i += 1) out[i] = binary.charCodeAt(i);
    return out;
  }
  // Node without atob (older runtimes): Buffer is always present there.
  return new Uint8Array(Buffer.from(value, "base64"));
}

export function decodeGlyph(glyph: Glyph): DecodedGlyph {
  const cached = decodeCache.get(glyph);
  if (cached) return cached;
  const bytes = base64ToBytes(glyph.b);
  const stride = Math.ceil(glyph.w / 8);
  const mask = new Uint8Array(glyph.w * glyph.h);
  for (let y = 0; y < glyph.h; y += 1) {
    for (let x = 0; x < glyph.w; x += 1) {
      const byte = bytes[y * stride + (x >> 3)] ?? 0;
      mask[y * glyph.w + x] = (byte >> (7 - (x & 7))) & 1;
    }
  }
  const decoded: DecodedGlyph = { ...glyph, mask };
  decodeCache.set(glyph, decoded);
  return decoded;
}

/**
 * Latin-1 has no ellipsis in some of these faces' coverage assumptions, and
 * typographic punctuation arrives from anything pasted out of a Mac. Fall
 * back through a small chain rather than dropping characters silently.
 */
const FALLBACKS: Record<string, string[]> = {
  "…": ["..."],
  "’": ["'"],
  "‘": ["'"],
  "“": ['"'],
  "”": ['"'],
  "–": ["-"],
  "—": ["-"],
  "•": ["·", "*"],
};

/**
 * One drawable thing in a line: a glyph from the atlas, or a pictogram.
 *
 * Text and pictograms share one run so that measuring, wrapping, truncating
 * and drawing all agree about how wide "Collect the parcel 🥚" is. A separate
 * pass for symbols would have been a second opinion, and the two would drift.
 */
export type RunItem =
  | { kind: "glyph"; glyph: Glyph; advance: number }
  | {
      kind: "picto";
      picto: Pictogram;
      scale: number;
      advance: number;
      /** Side of the square the pictogram occupies, in pixels. */
      side: number;
    };

export interface ResolvedRun {
  items: RunItem[];
  /** Symbols with no pictogram, in the order they appeared. */
  unsupported: string[];
}

/** One pixel of air after a pictogram so it does not touch the next letter. */
const PICTOGRAM_BEARING = 1;

function pictoItem(picto: Pictogram, size: number): RunItem {
  const scale = pictogramScale(size);
  const side = PICTOGRAM_GRID * scale;
  return { kind: "picto", picto, scale, advance: side + PICTOGRAM_BEARING, side };
}

/**
 * Turn a string into things that can be drawn.
 *
 * The order of resort matters and is deliberate:
 *
 *   1. The atlas. Anything the vendored face actually draws is drawn as type.
 *   2. A pictogram. Emoji and symbols the panel has a drawing for.
 *   3. The punctuation fallback chain, for typographic quotes and dashes
 *      pasted out of a Mac.
 *   4. For anything else that looks like a symbol, the unsupported box, and
 *      the character is reported. For anything else that looks like a letter,
 *      a question mark, which is what this renderer has always done.
 *
 * Nothing is ever dropped silently. That was the old behaviour for emoji and
 * it is the behaviour this replaces: a note reading "Collect the parcel 🥚"
 * used to lose the egg with no trace on the panel and no warning in the
 * designer.
 */
export function resolveRun(atlas: FontAtlas, text: string): ResolvedRun {
  const items: RunItem[] = [];
  const unsupported: string[] = [];

  const glyphFor = (char: string): Glyph | undefined =>
    atlas.glyphs[String(char.codePointAt(0))];

  for (const char of text) {
    const codepoint = char.codePointAt(0) ?? 0;
    // Variation selectors, skin tones and the zero width joiner are not
    // symbols in their own right and must not each draw a box.
    if (isIgnoredCodepoint(codepoint)) continue;

    const direct = glyphFor(char);
    if (direct) {
      items.push({ kind: "glyph", glyph: direct, advance: direct.a });
      continue;
    }

    const picto = pictogramFor(char);
    if (picto) {
      items.push(pictoItem(picto, atlas.size));
      continue;
    }

    const chain = FALLBACKS[char];
    let handled = false;
    if (chain) {
      for (const candidate of chain) {
        const parts = [...candidate].map(glyphFor);
        if (parts.every((p): p is Glyph => p !== undefined)) {
          for (const part of parts) {
            items.push({ kind: "glyph", glyph: part, advance: part.a });
          }
          handled = true;
          break;
        }
      }
    }
    if (handled) continue;

    if (looksLikeSymbol(char)) {
      // A symbol this panel cannot draw. Kept visible, and named, so the
      // designer can decide what to do about it.
      unsupported.push(char);
      items.push(pictoItem(UNSUPPORTED_PICTOGRAM, atlas.size));
      continue;
    }

    // An unmapped letter: a visible question mark beats a silent hole.
    const question = atlas.glyphs["63"];
    if (question) items.push({ kind: "glyph", glyph: question, advance: question.a });
  }

  return { items, unsupported };
}

export function measureRun(items: readonly RunItem[]): number {
  let pen = 0;
  for (const item of items) pen += item.advance;
  return pen;
}

export function measureText(atlas: FontAtlas, text: string): number {
  return measureRun(resolveRun(atlas, text).items);
}

/** Which symbols in this string the panel has no drawing for. */
export function unsupportedSymbols(atlas: FontAtlas, text: string): string[] {
  return resolveRun(atlas, text).unsupported;
}

/** Collapse whitespace and clamp length, exactly as the composer's clean(). */
export function clean(value: unknown): string {
  return String(value).split(/\s+/).filter(Boolean).join(" ").slice(0, 500);
}

/**
 * Truncate with a trailing ellipsis so the result fits maxWidth.
 *
 * Kept for the few places that genuinely want a hard cut, but note that the
 * text layer above this one prefers to report an overflow rather than call
 * it: a silent truncation on frozen e-paper ink hides the fact that the user
 * wrote something longer.
 */
export function fitText(
  atlas: FontAtlas,
  value: string,
  maxWidth: number,
): string {
  const text = clean(value);
  if (measureText(atlas, text) <= maxWidth) return text;
  const chars = [...text];
  while (chars.length > 0) {
    chars.pop();
    const candidate = `${chars.join("")}…`;
    if (measureText(atlas, candidate) <= maxWidth) return candidate;
  }
  return "";
}

/**
 * Greedy word wrap to a pixel width.
 *
 * A word that cannot fit on a line of its own is broken between characters
 * rather than dropped, and the caller is told: `hardBroken` is how the text
 * layer knows to raise an overflow warning instead of quietly mangling a long
 * sensor name.
 */
export function wrapText(
  atlas: FontAtlas,
  value: string,
  maxWidth: number,
): { lines: string[]; hardBroken: boolean } {
  const text = clean(value);
  if (text.length === 0) return { lines: [], hardBroken: false };
  if (maxWidth <= 0) return { lines: [text], hardBroken: true };

  const lines: string[] = [];
  let hardBroken = false;
  let current = "";

  const pushCurrent = (): void => {
    if (current.length > 0) {
      lines.push(current);
      current = "";
    }
  };

  for (const word of text.split(" ")) {
    const candidate = current.length === 0 ? word : `${current} ${word}`;
    if (measureText(atlas, candidate) <= maxWidth) {
      current = candidate;
      continue;
    }
    pushCurrent();

    if (measureText(atlas, word) <= maxWidth) {
      current = word;
      continue;
    }

    // The word alone is wider than the box. Break it at the last character
    // that fits, and remember that we had to.
    hardBroken = true;
    let piece = "";
    for (const char of word) {
      const next = piece + char;
      if (piece.length > 0 && measureText(atlas, next) > maxWidth) {
        lines.push(piece);
        piece = char;
      } else {
        piece = next;
      }
    }
    current = piece;
  }

  pushCurrent();
  return { lines, hardBroken };
}
